import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Form from '@/components/Form'
import Signup from '@/components/Sign-Up'
import App from '@/components/GetApp'
import FooterInstagram from '@/components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="Instagram-login-layout" content="Generated by create next app, edited into a mockup of instagram's login page" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.mainContainer}>
          <div className={styles.imageContainer}>
            <img className={styles.phoneMockup} src={'/images/phonemock.png'} alt="2 phones" priority/>
          </div>

          <main className={styles.main}>
            <div>

              <Form/>
              <br className={styles.formSpacing}></br>
              <Signup/>
              <br className={styles.formSpacing}></br>
              <App/>

            </div>
          </main>
      </div>
      
      <footer className={styles.footerDisplay}>
      <FooterInstagram/>
      </footer>
    </>
  )
}
